In [1]:
import numpy as np
from pydrake.geometry.optimization import HPolyhedron
from pydrake.solvers import MathematicalProgram
import pydrake.solvers as solvers_drake
import yaml

gurobi_solver = solvers_drake.GurobiSolver()
gurobi_license = gurobi_solver.AcquireLicense()


In [2]:
A = np.hstack((np.array(range(10))[:,np.newaxis],np.array(range(10))[:,np.newaxis]))
b = np.array(range(10))

In [3]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
X = HPolyhedron(A,b)

In [5]:
d = np.array(range(10))
moved_in = np.random.choice([True,False], size = 10)

In [6]:
moved_in

array([ True, False,  True, False,  True, False, False, False,  True,
       False])

In [7]:
X_shuffled = X.ShuffleHyperplanes(d,moved_in,0)

INFO:drake:d: 0
INFO:drake:d: 1
INFO:drake:d: 2
INFO:drake:d: 3
INFO:drake:d: 4
INFO:drake:d: 5
INFO:drake:d: 6
INFO:drake:d: 7
INFO:drake:d: 8
INFO:drake:d: 9
INFO:drake:moved_in: true
INFO:drake:moved_in: false
INFO:drake:moved_in: true
INFO:drake:moved_in: false
INFO:drake:moved_in: true
INFO:drake:moved_in: false
INFO:drake:moved_in: false
INFO:drake:moved_in: false
INFO:drake:moved_in: true
INFO:drake:moved_in: false


In [8]:
X_shuffled.A()

array([[0., 0.],
       [2., 2.],
       [1., 1.],
       [5., 5.],
       [9., 9.],
       [8., 8.],
       [4., 4.],
       [7., 7.],
       [6., 6.],
       [3., 3.]])

In [9]:
X_shuffled.b()

array([0., 2., 1., 5., 9., 8., 4., 7., 6., 3.])

In [10]:
moved_in

array([ True,  True,  True, False, False, False,  True, False, False,
       False])

In [12]:
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
X.IsEmpty()

False

In [9]:
X.MakeUnitBox(4)